### ISSUE TITLE
Chrome OS (Beta/Dev) 85 removed support

### ISSUE THREAD

**Issue by RedcatPhoenix2** [reynhout/chrx#102] opened 2020-07-27 14:48 UTC
So... I was going to reinstall ubuntu 18.04 and well... after the Chrome OS update, it removed support for Chrx, please make a update to add support to Chrome OS 85 Beta/Dev versions!!!

**Comment by reynhout** [comment] 2020-07-27 14:54
Closing as dupe of #98 . Thanks for the info on these tickets.

**Closed by reynhout** 2020-07-27 14:54 UTC
