### ISSUE TITLE
sudoers missing on Ubuntu

### ISSUE THREAD

**Issue by Birk3n** [reynhout/chrx#30] opened 2016-12-15 22:26 UTC
When installing Ubuntu minimun/standard on Asus Chromebox CN60 there is no access to root or sudo.

**Comment by reynhout** [comment] 2016-12-15 23:53
Interesting, I'll look into it.

Do you have an acceptable workaround for the moment?

**Comment by Birk3n** [comment] 2016-12-16 08:21
I guess its possible to boot into recovery mode und change root pass or usermod the user. 

Unfortunately i cant boot into recovery, because my keyboard isnt working in grubmenu (could be another bug)

**Comment by Birk3n** [comment] 2016-12-16 08:39
Im gonna look at the log in the evening and post it

**Comment by Birk3n** [comment] 2016-12-20 16:11
Sorry I'm super late. The group "lpadmin" is missing in ubuntu und thats why the user dont have any groups. Maybe do an exeption for ubuntu or check if groups exists before

**Comment by reynhout** [comment] 2016-12-22 19:49
Ah, I see. The problem is that the Ubuntu metapackage you chose (minimal?), does not include the print related packages that add the `lpadmin` group. The standard desktop metapackage should have the group. If any groups in the specified list do not exist, the command exits without adding the user to *any* of them.

I've added a patch that adds the groups individually rather than all in one command. So if any individual adds fail, the others should still succeed.

Please let me know if this resolves the problem for you.

Thanks for the report!

**Comment by reynhout** [comment] 2016-12-30 19:23
Closing, please re-open if problem persists.

**Closed by reynhout** 2016-12-30 19:23 UTC
