### ISSUE TITLE
chrx Ubuntu install/boot error

### ISSUE THREAD

**Issue by JohnSandel** [reynhout/chrx#31] opened 2017-01-06 03:21 UTC
Seconding another user's thanks for chrx. This is a terrific tool for a newbie like me. 

And I'd like to request a way to install Elementary OS (latest) via chrx. I hope you can find the time to make that possible.

I'm testing distros on an Asus Chromebox—Panther, Haswell @1.4GHz—which chrx makes a snap. (Using a live USB on this machine is a series of headaches … it's much easier to install distros from the internet.)

With chrx I've succeeded in installing Gallium, Lubuntu & Fedora—all using your commands verbatim.

Ubuntu _appears_ to install—chrx reports "no errors"—then fails to boot, every time, immediately after the GRUB screen. I've had variants on the error message 3 times now:

ash: write error: No such device

ash: write error: No such device
[	4.942123] usb 1-4: string descriptor 0 read error: -22

ash: write error: No such device
[	5.369873] usb 1-4: string descriptor 0 read error: -22

To be scrupulous, I did a recovery from USB of Chrome OS between all installs of Linux. Later, I tried  variants on your command, for releases 15.04 ("No longer supported"), 15.10 (same), 16.04 and 16.10. No dice—same error message.

Any suggestions how I can get Ubuntu to install &/or boot properly using chrx?

JS

**Comment by reynhout** [comment] 2017-01-06 03:40
Hi, thanks for your report!

I am not sure what's going wrong with the install -- it's been a while since my last test of full Ubuntu.

It should be 100% safe and reliable to simply reinstall with chrx on top of a previous chrx install. No need to go all the way back to ChromeOS first. Saves a few minutes between tests, at least. I appreciate your scrupulousness though, clean tests are always helpful.

I will give full Ubuntu another try, hopefully this coming weekend, and get back to you.

Re: elementaryOS: Unfortunately, it's very unlikely without someone's help. I don't know whether the eOS folks would be supportive of the effort or not, but I would be glad to include them in chrx. I don't see myself having the time to do the work though.

**Comment by JohnSandel** [comment] 2017-01-06 03:52
Thanks, Andrew! I'm a big fan of chrx; it's a clever tool. I'll get ahold of the Elementary kids & ask them if they're open to chrx. 

Please do have a look at your install routine for Ubuntu … Ignorance prevents me from critiquing what's going on.

**Comment by reynhout** [comment] 2017-01-06 14:02
@JohnSandel I had some time and a spare machine last night, so I did a full Ubuntu install.

It was a Braswell machine, so the internal keyboard doesn't work on Ubuntu (requires a kernel patch from GalliumOS), but otherwise the system seemed to work properly. Booted, could log in, suspended, etc.

I also have a Haswell Chromebox that I can test (ZAKO, very similar to your PANTHER). It might take a couple days to free it up from its other tasks, but I'll get there. :)

**Comment by JohnSandel** [comment] 2017-01-06 15:59
Thank you for turning your mind to this. Do the error messages I posted mean anything to you?

**Comment by reynhout** [comment] 2017-01-06 20:18
Those error messages are typical on working machines as well. The problem will likely lie somewhere else.

**Comment by JohnSandel** [comment] 2017-01-11 21:39
Following up here for lack of a more direct way to message you. @CassidyJames, one of the Elementary principals, told me on Twitter that they're provisionally open to your making Elementary available for install via chrx:

"We have to see how it's distributed [i.e., how chrx would make their OS available]. My initial thought's that it is OK. Be sure to consult elementary.io/brand."

So, not the last word—& you may not have the time or inclination to include Elementary—but I wanted to make you guys aware of each other. (Elementary is pretty popular with Chromebook/-box owners.) BTW, I was plain on Twitter that I don't work with you or speak for you.

If you have any news on the chrx implementation of Ubuntu 16.x, let me know. Thank you!

**Comment by reynhout** [comment] 2017-01-12 00:02
@JohnSandel Thanks for the follow-up. I have received a few requests for elementaryOS, so I know there's interest.

I'm still waiting for a chance to test on my ZAKO here (it isn't strictly a test device), but I'll let you know when I do. I *have* successfully tested full Ubuntu on a PEPPY (also Haswell). The differences are minimal but not zero.

**Comment by JohnSandel** [comment] 2017-01-12 00:28
I leave it to you. Is GitHub the best place to message you? Are you on, e.g., Twitter or somewhere else?

**Comment by reynhout** [comment] 2017-01-12 02:34
Not Twitter, but general chrx questions/support/discussion often happen on the old ChrUbuntu subreddit: https://www.reddit.com/r/chrubuntu/

**Comment by reynhout** [comment] 2017-03-30 16:56
I cannot repro this on ZAKO. Ubuntu seems to work properly for me. Something might have changed in their packaging since the issue was reported? I'm running full/UEFI firmware on this device, so it's possible that has an effect.

(I have no news on elementaryOS either, it remains interesting but realistically not imminent. There's an eOS-specific ticket open at #27.)

I'm going to close this ticket for now. If the problem persists for you on PANTHER, please re-open and tell me as much as you can about your install environment so I can try again to repro. Thanks!

**Closed by reynhout** 2017-03-30 16:56 UTC

**Comment by izk8** [comment] 2018-10-09 00:44
I just had the same issue as @JohnSandel's original issue.

 Well, to reproduce it, I changed the` -r 16.04` to `-r 16.04.5`, as the simple 16.04 generated url doesn't resolve. 

Some notes: 
ASUS Chromebook Flip 
C302CA-DHM4 12.5-Inch Touchscreen Intel Core m3 with 64GB storage and 4GB RAM
Cave model 

I had gallium installed via chrx and working well for over a year; just wanted to try out ubuntu.

**Comment by jacobhq** [comment] 2024-03-03 16:58
> Well, to get a successful build, I changed the -r 16.04 to -r 16.04.5, as the 16.04 generated url doesn't resolve.

That was super helpful. Thanks!!
